name: Deploy Discord Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the Python version

      - name: Install dependencies
        run: |
          //python -m pip install --upgrade pip
          //pip install discord.py requests beautifulsoup4

      - name: Run bot
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.Hello }}
          STEAM_API_KEY: ${{ secrets.Hi }}
        run: python bot.py
